#!/bin/bash
kafka-avro-console-consumer --bootstrap-server localhost:9092 --from-beginning --topic privat-dagpenger-journalpost-mottatt-alpha --property schema.registry.url=http://localhost:8081 --consumer.config config-local-user.properties
