rootProject.name = "dagpenger-monorepo"

includeBuild("dagpenger-events")
includeBuild("dagpenger-funksjonelle-tester")
includeBuild("dagpenger-joark-mottak")
includeBuild("dagpenger-streams")
includeBuild("dp-arena-sink")
includeBuild("dp-biblioteker")
includeBuild("dp-doh")
includeBuild("dp-grunnbelop")
includeBuild("dp-inntekt")
includeBuild("dp-kalkulator-frontend")
includeBuild("dp-inntekt-klassifiserer")
includeBuild("dp-kalkulator-api")
includeBuild("dp-oppslag-arbeidssoker")
includeBuild("dp-oppslag-vedtak")
includeBuild("dp-regel-api")
includeBuild("dp-regel-api-arena-adapter")
includeBuild("dp-regel-grunnlag")
includeBuild("dp-regel-minsteinntekt")
includeBuild("dp-regel-periode")
includeBuild("dp-regel-sats")
includeBuild("dp-speider")
includeBuild("dp-vedtakresultat-lytter")
