rootProject.name = "dagpenger-monorepo"

includeBuild("dagpenger-events")
includeBuild("dagpenger-funksjonelle-tester")
includeBuild("dp-inntekt-api")
includeBuild("dp-datalaster-inntekt")
includeBuild("dagpenger-joark-mottak")
includeBuild("dagpenger-journalforing-arena")
includeBuild("dagpenger-journalforing-ferdigstill")
includeBuild("dagpenger-journalforing-gsak")
includeBuild("dagpenger-journalforing-manuell")
includeBuild("dagpenger-journalforing-ruting")
includeBuild("dagpenger-journalforing-skanning")
includeBuild("dagpenger-oppslag")
includeBuild("dagpenger-streams")
includeBuild("dagpenger-metrics")
includeBuild("dp-regel-api")
includeBuild("dp-regel-api-arena-adapter")
includeBuild("dp-regel-minsteinntekt")
includeBuild("dp-regel-periode")
includeBuild("dp-regel-grunnlag")
includeBuild("dp-regel-sats")
includeBuild("dp-kafka-offset-monitor")
includeBuild("dp-biblioteker")
