@startgantt
skinparam dpi 200
ganttscale weekly
Labels on first column

Project starts 2022-01-01

[SBS EOL] happens 2022-04-01 and is colored in Red
[Rekker vi å bli ferdig med ny søknadsdialog?] happens 2022-02-01 and is colored in Blue

-- Frontend --
[Lage ny frontend] starts 2022-01-01 and ends 2022-03-01 and is colored in Green

-- Backend --
[Utvikle det som trengs i Quiz for MVP-en] starts 2022-01-01 and ends 2022-03-01 and is colored in Green
then [Sette aktivt i prod] lasts 2 week and is colored in Green
then [Jobbe med neste versjon av søknadsdialogen] lasts 10 week

-- Design --
[Skisser med nytt designsystem (samme rekkefølge)] starts 2022-01-01 and ends 2022-02-01 and is colored in Green
then [Finne bedre måte å oppgi arbeidsforhold] lasts 4 weeks and is colored in Green
then [Brukerteste det nye designet] ends 2022-03-25 and is colored in Green
then [Brukerteste helt nye rekkefølge] lasts 8 weeks
[Innsikt og utforsking for versjon 2] starts 2022-04-02 and ends 2022-07-01

-- Annet --
[Målinger av dagens brukeropplevelse] lasts 2 weeks

@endgantt
