#!/bin/bash
kafka-avro-console-producer --broker-list localhost:9092  --topic privat-dagpenger-journalpost-mottatt-alpha --property schema.registry.url=http://localhost:8081 --producer.config config-local-user.properties --property value.schema='{
  "type" : "record",
  "name" : "Behov",
  "namespace" : "no.nav.dagpenger.events.avro",
  "fields" : [ {
    "name" : "behovId",
    "type" : "string"
  }, {
    "name" : "henvendelsesType",
    "type" : {
      "type" : "record",
      "name" : "HenvendelsesType",
      "fields" : [ {
        "name" : "søknad",
        "type" : [ "null", {
          "type" : "record",
          "name" : "Søknad",
          "fields" : [ {
            "name" : "vedtakstype",
            "type" : [ "null", {
              "type" : "enum",
              "name" : "Vedtakstype",
              "symbols" : [ "NY_RETTIGHET", "GJENOPPTAK" ]
            } ],
            "default" : null
          }, {
            "name" : "rettighetsType",
            "type" : [ "null", {
              "type" : "enum",
              "name" : "Rettighetstype",
              "symbols" : [ "ORDINÆRE_DAGPENGER", "DAPENGER_UNDER_PERMITERING", "PERMITERING_FRA_FISKEINDUSTRIEN", "DAGPENGER_VED_KONKURS", "EKSPORT" ]
            } ],
            "default" : null
          } ]
        } ],
        "default" : null
      }, {
        "name" : "ettersending",
        "type" : [ "null", {
          "type" : "record",
          "name" : "Ettersending",
          "fields" : [ {
            "name" : "rettighetsType",
            "type" : [ "null", "Rettighetstype" ],
            "default" : null
          } ]
        } ],
        "default" : null
      }, {
        "name" : "annet",
        "type" : [ "null", {
          "type" : "record",
          "name" : "Annet",
          "fields" : [ ]
        } ],
        "default" : null
      } ]
    }
  }, {
    "name" : "mottaker",
    "type" : [ "null", {
      "type" : "record",
      "name" : "Mottaker",
      "fields" : [ {
        "name" : "identifikator",
        "type" : "string"
      } ]
    } ],
    "default" : null
  }, {
    "name" : "behandleneEnhet",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "fagsakId",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "gsaksakId",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "journalpost",
    "type" : [ "null", {
      "type" : "record",
      "name" : "Journalpost",
      "fields" : [ {
        "name" : "journalpostId",
        "type" : "string"
      }, {
        "name" : "dokumentListe",
        "type" : [ "null", {
          "type" : "array",
          "items" : {
            "type" : "record",
            "name" : "Dokument",
            "fields" : [ {
              "name" : "dokumentId",
              "type" : "string"
            }, {
              "name" : "navSkjemaId",
              "type" : [ "null", "string" ],
              "default" : null
            } ]
          }
        } ],
        "default" : null
      } ]
    } ],
    "default" : null
  }, {
    "name" : "trengerManuellBehandling",
    "type" : "boolean",
    "default" : false
  } ]
}'








