name: "attest-sign"
description: "Generate SBOM, attest and sign docker image"
branding:
  icon: "lock"
  color: "green"
inputs:
  image:
    description: "Docker image reference"
    required: false
  digest:
    description: "Docker image digest"
    required: true
  team:
    description: "Team"
    required: true
outputs:
  sbom:
    description: "SBOM.json in cyclonedx format"
    value: ${{ steps.attest-sign.outputs.sbom }}
runs:
  using: "composite"
  steps:
    - name: NAIS login
      uses: nais/login@v0
      id: login
      with:
        team: ${{ inputs.team }}

    - id: image
      shell: bash
      run: |
        if [[ -n "${{ inputs.image }}" ]]; then
          echo "IMAGE=${{ inputs.image }}" >> $GITHUB_OUTPUT
        else
          echo "::warning::No 'image' provided. Falling back to repo name. This will be removed in v2."
          repo_name="${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER\//}"
          repo_name="$(tr "[:upper:]" "[:lower:]" <<< "$repo_name")"
          echo "IMAGE=${{ steps.login.outputs.registry }}/$repo_name" >> $GITHUB_OUTPUT
        fi

    - name: Generate SBOM, attest and sign image
      id: attest-sign
      uses: nais/attest-sign@v1
      with:
        image_ref: ${{ steps.image.outputs.IMAGE }}@${{ inputs.digest }}
