rootProject.name = "dagpenger-saksbehandling"

includeBuild("dp-behovsakkumulator")
includeBuild("dp-datalaster-subsumsjonbrukt")
includeBuild("dp-inntekt-api")
includeBuild("dp-inntekt-klassifiserer")
includeBuild("dp-oppslag-arbeidsforhold")
includeBuild("dp-oppslag-arbeidssoker")
includeBuild("dp-oppslag-person")
includeBuild("dp-oppslag-soknadfakta")
includeBuild("dp-oppslag-ytelser")
includeBuild("dp-oppslag-vedtak")
includeBuild("dp-regel-api")
includeBuild("dp-regel-api-arena-adapter")
includeBuild("dp-regel-grunnlag")
includeBuild("dp-regel-minsteinntekt")
includeBuild("dp-regel-periode")
includeBuild("dp-regel-sats")
includeBuild("dp-regel-tapt-arbeidstid")
includeBuild("dp-regel-virkningstidspunkt")
includeBuild("dp-saksbehandling")
includeBuild("dp-soknad-mottak")
includeBuild("dp-vedtak-oppslag")
includeBuild("dp-vedtakresultat-lytter")
