#!/bin/bash
TOPIC=${1:-dagpenger}

docker-compose exec kafka kafka-topics \
        --create \
        --topic $TOPIC \
        --partitions 1 \
        --replication-factor 1 \
        --if-not-exists \
        --zookeeper zookeeper:2181
