#!/bin/bash

TOPIC=${1:-dagpenger}

PARAMS=(
        --broker-list kafka:9092
        --topic $TOPIC
        --property schema.registry.url=http://schema-registry:8081
        --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
)

docker-compose exec schema-registry \
        kafka-avro-console-producer \
        "${PARAMS[@]}"
