theme: jekyll-theme-cayman
markdown: kramdown
collections:
  adr:
    output: true
    permalink: /:collection/:name
  jenkins:
    output: true
    permalink: /:collection/:name
  postmorten:
    output: true
    permalink: /:collection/:name
  howtos:
    output: true
    permalink: /:collection/:name
kramdown:
  input: GFM
  auto_ids: true
  highlighter: rouge
